sudo: required
language: bash
services:
  - docker
before_script:
  - docker build --tag ${KBC_APP_REPOSITORY} .
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  

notifications:
  slack:
    secure: Rl0OT6rNyyTkhG/P8EsfmpoaTIBUH4R7W1QphnU5mBZIa7OyTuE8hYK6AaevNgIvxyhcmITtAiNQu1cXy7oziMd91xMIV4LmUYBlIyuLQPlbkitdHYmCwR3wfGgMfRHDcfqzp8SKx1Wc+ZR4QY4VLTHcZxSRhKjNffe8qn1UWwr5h7PQyiXjUW/N6lF1aFT1576aBrhpUUMnEAmyfGqDvOfI9T4wmV3LajpmQVrKfo/Ve/FUZziWrvMuuXBRdcIZzszctZaD3dvuq9CswcLoySIRUlaTGVAjlzuHMG44TnYqb12FT2/O/h/aN9kEeFaP+Mm74lyip93jB/WzyMGUssRmTJ37rJO0dF8n9nz6SxsSRZJf8Horz9lDRcjnvbWR3QlB7b1vLdZsgfskR89s2l1kY00inuMKOmW+pDGeRUS+5gFmyFC6vBQ7gFVZIA0ehx1kaMBZIav0/HgXAzvgjJxstL9oWiVA+b9L9Lk+YrJHyCRsQRCUs8XRyfF+14eSDnIQn1wAQEaLcU38h8qb8xDVjWNWwtiBsbJmrZluKlRAv88R6nI1lKMwbr+CUeqHJErtnyxakJ5FfB+RxYz+ngdSfCbZ8Yi04etJzDJ9T3xnozBZHNtvel2X1hXpLiJ6Fh4eoAezQlsFehnKLZpwu8vMijwBRIawRdR/wHYrxbU=
