pool:
  vmImage: ubuntu-latest

variables:
- name: imageTag
  value: ${{ replace(variables['Build.SourceBranch'],'refs/tags/','') }}
- name: isTagBuild
  value: ${{ startsWith(variables['Build.SourceBranch'],'refs/tags/') }}
- name: dockerRegistryServiceConnection
  value: '85ab7e7c-62ce-49e0-b201-bf56e6f3949e'
- name: imageRepository
  value: 'docker-custom-julia'

trigger:
  - refs/tags/*

steps:
- script: docker info
  displayName: 'Info'

- task: Docker@2
  inputs:
    containerRegistry: 'keboola-4338'
    repository: 'docker-custom-julia'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)

- script: docker build --tag keboola/docker-custom-julia .
  displayName: 'Build'

- script: |
    docker login -u="$(QUAY_USERNAME)" -p="$(QUAY_PASSWORD)" quay.io
    docker tag $(KBC_APP_REPOSITORY) quay.io/$(KBC_APP_REPOSITORY):$(imageTag)
    docker tag $(KBC_APP_REPOSITORY) quay.io/$(KBC_APP_REPOSITORY):latest
    docker images
    docker push quay.io/$(KBC_APP_REPOSITORY):$(imageTag)
    docker push quay.io/$(KBC_APP_REPOSITORY):latest
  condition: eq(variables['isTagBuild'], 'true')
  displayName: 'Push latest to quay.io'
   
- task: Docker@2
  inputs:
    containerRegistry: 'keboola-4338'
    repository: 'docker-custom-julia'
    command: 'push'
    tags: '$(imageTag)'
  condition: eq(variables['isTagBuild'], 'true')
  displayName: 'Push latest to ACR'
  